#!/usr/bin/env bash

source /etc/profile

set -e

CWD="$(pwd)"
cd $(dirname "$(realpath "${BASH_SOURCE[0]}")")
source ./get-cert/base.sh

if [ -z "$1" ]; then
	usage
fi

export DRY_RUN=''
while getopts ":df:" o; do
	case "${o}" in
        d)
		export DRY_RUN='--staging'
		;;
        f)
		CFG="$OPTARG"
		;;
	\?)
		usage "Invalid option: -$OPTARG"
		exit 1
		;;
	:)
		usage "Option -$OPTARG requires an argument."
		;;
	*)
		usage
		;;
    esac
done

if [ -n "${CFG}" ]; then
	if [ -e "$CFG" ] ; then
		load-config "$CFG"
	elif [ -e "$CWD/$CFG" ] ; then
		load-config "$CWD/$CFG"
	else
		die "config file '$CFG' not exists"
	fi
fi

for SUB_DOMAIN; do true ; done

if [ -z "${SUB_DOMAIN}" ] || [ "${SUB_DOMAIN}" = "${CFG}" ]; then
	usage "you must provide a sub domain name"
fi

check_variables BASE_DOMAIN EMAIL DNSMASQ_CONFIG_DIR DNSMASQ_SERVICE_CONTROL

export DOMAIN="${SUB_DOMAIN}.${BASE_DOMAIN}"

cd get-cert
expect action.expect "${DOMAIN}"

