#!/usr/bin/env bash

source /etc/profile
set -e

source $(dirname "$(realpath "${BASH_SOURCE[0]}")")/get-cert/base.sh

load-arguments "$@"

check_variables BASE_DOMAIN EMAIL

cd "$ROOT"
expect get-cert/action.expect "${ARG_HOST}" "${BASE_DOMAIN}"

