#!/usr/bin/env bash

set -e

source $(dirname "$(realpath "${BASH_SOURCE[0]}")")/get-cert/base.sh

load-arguments "$@"

check_variables CNAME_TARGET BASE_DOMAIN

cd "$ROOT"
. get-cert/put_dns_config.sh "${ARG_HOST}" "CNAME" "${CNAME_TARGET}"

