#!/usr/bin/env bash

set -e

CWD="$(pwd)"
cd $(dirname "$(realpath "${BASH_SOURCE[0]}")")
source ./get-cert/base.sh

if [ -z "$1" ]; then
	usage
fi


while getopts ":df:" o; do
	case "${o}" in
	f)
		CFG="$OPTARG"
		;;
	\?)
		usage "Invalid option: -$OPTARG"
		exit 1
		;;
	:)
		usage "Option -$OPTARG requires an argument."
		;;
	*)
		usage
		;;
	esac
done

if [ -n "${CFG}" ]; then
	if [ -e "$CFG" ] ; then
		load-config "$CFG"
	elif [ -e "$CWD/$CFG" ] ; then
		load-config "$CWD/$CFG"
	else
		die "config file '$CFG' not exists"
	fi
fi

for SUB_DOMAIN; do true ; done

if [ -z "${SUB_DOMAIN}" ] || [ "${SUB_DOMAIN}" = "${CFG}" ]; then
	usage "you must provide a sub domain name"
fi

check_variables BASE_DOMAIN CNAME_TARGET DNSMASQ_CONFIG_DIR DNSMASQ_SERVICE_CONTROL

export DOMAIN="${SUB_DOMAIN}.${BASE_DOMAIN}"

cd get-cert
echoo "
cname=${DOMAIN},${CNAME_TARGET}
" | \
bash put_dns_config.sh "cname-${SUB_DOMAIN}"

